async:
    dao:
     mapperLocations: /mapper
     basePackages: com.tg.mapper
     username: root
     host: localhost
     port: 3306
     password: admin
     database: test
     maxTotal: 12
     maxIdle: 12
     minIdle: 1
     maxWaitMillis: 10000



